HRIS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as userViews
from django.contrib.auth import views as authViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('registration/', userViews.register, name="reg"),
    path('login/', authViews.LoginView.as_view(template_name='users/auth.html'), name='user'),
    path('exit/', authViews.LogoutView.as_view(template_name='main/index.html'), name='exit'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('record/', include('request.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

request/urls.py
from django.urls import path

from .views import RecordView, add_orders, DeleteApplicationView, Edit_application

app_name = "request"

urlpatterns = [
    path('', RecordView.as_view(), name="record"),
    path('add_orders', add_orders, name="add_orders"),
    path('delete_application/<int:application_id>/', DeleteApplicationView.as_view(), name="delete_application"),
    path('edit_application/<int:app_id>/', Edit_application, name='edit_application')
]

request/models.py
from django.db import models

# Create your models here.

request/forms.py
from django import forms
from bd.models import *

class Application_forms(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['description'].widget.attrs.update({'placeholder': 'Введите выдаваему сотруднику сумму'})


    class Meta:
        model = Application
        fields = ['worker', 'number_cab', 'description']


class ApplicationFormEdit(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['worker', 'number_cab', 'description']

request/views.py
#from db.models import Status
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from .forms import Application_forms, ApplicationFormEdit
from bd.models import Application, office
from django.views import View


class RecordView(FormView):
    template_name = 'record.html'
    form_class = Application_forms
    success_url = '/record'

    def get(self, request, *args, **kwargs):
        user_id = request.user.id
        user_applications = Application.objects.filter(auth_user_id=user_id)
        all_offices = office.objects.all()
        form = Application_forms

        context = {
            'all_offices': all_offices,
            'user_applications': user_applications,
            'form': form,

        }
        return render(request, self.template_name, context)


def add_orders(request):
    if request.POST:
        form = Application_forms(data=request.POST)

        if form.is_valid():
            obj = form.save(commit=False)
            obj.auth_user_id = request.user.id
            obj.save()

    return redirect('/record/')


class DeleteApplicationView(View):
    def post(self, request, application_id):
        try:
            application = Application.objects.get(id=application_id)
            if application.auth_user_id == request.user.id:
                application.save()
                # application.delete()
                print(f"Заявка {application_id} удалена успешно.")
        except Application.DoesNotExist:
            pass
        return redirect('/record#record')


def Edit_application(request, app_id):
    print(app_id)

    try:
        application = Application.objects.get(id=app_id)
    except Application.DoesNotExist:
        application = None

    if request.method == 'POST':
        form = ApplicationFormEdit(request.POST, instance=application, initial={'number_cab': application.number_cab,
                                                                                'description': application.description})
        if form.is_valid():
            form.save()
            return redirect('request:record')
    else:
        form = ApplicationFormEdit(instance=application, initial={'number_cab': application.number_cab,
                                                                  'description': application.description})
        print(form)

    context = {
        'form': form,
        'app': application,
    }
    return render(request, 'record.html', context)

request/templates/record.html
{% extends 'main/start.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}{% endblock %}
{% block body %}

<div class="container">
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item" role="presentation">
            <a class="nav-link active" id="add_application-tab" data-bs-toggle="tab" href="#add_application" role="tab" aria-controls="add_application" aria-selected="true">Выдать зарплату</a>
        </li>
        <li class="nav-item" role="presentation">
            <a class="nav-link" id="record-tab" data-bs-toggle="tab" href="#record" role="tab" aria-controls="record" aria-selected="false">Мои выдачи</a>
        </li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane fade show active" id="add_application" role="tabpanel" aria-labelledby="add_application-tab">
            <div class="card w-100">
                <div class="card-body">
                    <h2>Создание новой выдачи</h2>
                    <form method="post" action="{% url 'request:add_orders' %}">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="w-100 btn btn-lg btn-primary mt-4" type="submit" id="submit" onclick="clicks();">Создать</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="record" role="tabpanel" aria-labelledby="record-tab">
            <div class="card w-100 mt-4">
                <div class="card-body">
                    <h2>Ваши выдачи</h2>
                    <ul class="list-group">
                        {% for app in user_applications %}
                            <li class="list-group-item my-2 rounded">
                                <div class="fw-bold bg-status-{{ app.status_application.id }} p-2 w-25">Номер выдачи:
                                    <span class="fw-normal">
                                        {{ app.id }}
                                    </span>
                                </div>
                                <div class="fw-bold p-2">Дата: <span class="fw-normal">{{ app.date }}</span></div>
                                <div class="fw-bold p-2">Сотрудник: <span class="fw-normal">{{ app.worker }}</span></div>
                                <div class="fw-bold p-2">Зарплата: <span class="fw-normal">{{ app.description }}</span></div>
                                <div class="fw-bold p-2">Отдел: <span class="fw-normal">{{ app.number_cab }}</span></div>

                            </li>
                            <div class="d-flex justify-content-between my-2">
                                {% if app.status_application.id == 1 %}
                                <div class="d-flex justify-content-between align-items-center">
                                    
                                    <button class="btn btn-primary me-2" type="button" onclick="editApplication({{ app.id }})">Редактировать</button>
                                    
                                    <form method="post" action="{% url 'request:delete_application' app.id %}">
                                        {% csrf_token %}
                                        <button class="btn btn-danger" type="submit">Удалить</button>
                                    </form>
                                </div>
                                {% endif %}
                            </div>
                            
                            <div class="p-1 bg-secondary w-100 rounded"></div>

                            <form method="post" class="edit-form w-25 my-2" action="{% url 'request:edit_application' app.id %}" style="display: none;">
                                {% csrf_token %}
                                <input type="hidden" name="editId" value="{{ app.id }}">
                                <div class="form-floating my-2">
                                    <select class="form-select" name="number_cab" id="floatingSelect" aria-label="Floating label select example">
                                      {% for cabinet in all_offices %}
                                      <option value="{{ cabinet.id }}" {% if cabinet.id == app.number_cab_id %} selected {% endif %}>{{ cabinet.number }}</option>
                                      {% endfor %}
                                    </select>
                                    <label for="floatingSelect">Выберите отдел</label>
                                </div>
                                <div class="form-floating my-2">
                                    <textarea class="form-control" placeholder="Опишите проблему" name="description" id="floatingTextarea2" style="height: 100px">{{ app.description }}</textarea>
                                    <label for="floatingTextarea2">Опишите подробности</label>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <button type="submit" class="btn btn-primary" onclick="edit_form();">Сохранить</button>
                                    <button type="button" class="btn btn-secondary" onclick="cancelEdit(this)">Отмена</button>
                                </div>
                            </form>

                        {% empty %}
                            <p>У вас нет активных выдач.</p>
                        {% endfor %}
                    </ul>
                </div>
            </div>    
        </div>
    </div>
</div>

<script src="{% static 'js/main.js' %}"></script>
<script>
    deleteAsteriskFields()
    itemFormRow()
</script>
{% endblock %}