HRIS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as userViews
from django.contrib.auth import views as authViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('registration/', userViews.register, name="reg"),
    path('login/', authViews.LoginView.as_view(template_name='users/auth.html'), name='user'),
    path('exit/', authViews.LogoutView.as_view(template_name='main/index.html'), name='exit'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('record/', include('request.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from . import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
                path('', views.index, name='home'),
                path('accounts/', include('django.contrib.auth.urls')),
                path('staffs/', views.staff, name='staff'),
                path('orders/', StaffsView.as_view(), name='orders'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

request/urls.py
from django.urls import path

from .views import RecordView, add_orders, DeleteApplicationView, Edit_application

app_name = "request"

urlpatterns = [
    path('', RecordView.as_view(), name="record"),
    path('add_orders', add_orders, name="add_orders"),
    path('delete_application/<int:application_id>/', DeleteApplicationView.as_view(), name="delete_application"),
    path('edit_application/<int:app_id>/', Edit_application, name='edit_application')
]

main/forms.py
from django import forms
from bd.models import *

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class StaffsForm(forms.ModelForm):
    class Meta:
        model = Staff
        fields = ['name', 'type', 'character', 'image']


class RegisterUserForms(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1')


class LoginUserForms(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

main/views.py
from django.shortcuts import render
from bd.models import Staff
from .forms import StaffsForm
from django.views.generic import FormView
from django.urls import reverse_lazy
def index(request):
    return render(request, 'main/index.html')


def staff(request):
    staffs = Staff.objects.all()
    return render(request, 'main/Staff.html', {'staffs': staffs})


class StaffsView(FormView):
    template_name = 'orders.html'
    form_class = StaffsForm
    success_url = reverse_lazy("staff")

    def form_valid(self, form):
        if form.is_valid():
            print(self.request.FILES)
            form.save()
            return super().form_valid(form)
        else:
            return self.form_invalid(form)

main/templates/main/Staff.html
{% extends 'main/start.html' %}

{% load static %}

{% block title %}
  <title>Сотрудники</title>
{% endblock %}

{% block body %}
<div class="container border border-1 rounded p-4" >
  <div class="row" style="display: grid; grid-template-columns: repeat(3,1fr); column-gap: 20px; row-gap: 20px;">
    {% for el in staffs %}
    <div class="card col">
      <h1>{{ el.name }}</h1>
      <p>{{ el.character }}</p>
      <img src="{{ el.image.url }}" class="card-img-top p-2" width="100" height="350" alt="123" title="123">
      
  
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}  

main/templates/main/index.html
{% extends 'main/start.html' %}



{% load static %}

{% block title %}
    <title>HRIS</title>
{% endblock %}

{% block body %}


<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">ИС отдела кадров</h1>
            <p class="lead text-muted">Учет списка сотрудников</p>
            <p>
                  {% if user.is_authenticated %}
                  <a href="{% url 'staff' %}" class="btn btn-primary my-2">Сотрудники</a>
                  {% else %}
                      <h1 class="lead text-muted">Перед использованием необходима регистрация</h1>
                      <a href="{% url 'reg' %}" class="btn btn-primary my-2">Зарегестрироваться</a>

                  {% endif %}


            </p>
        </div>
    </div>
</section>

{% endblock %}

main/templates/main/start.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">


    <script src="{% static 'main/js/main.js' %}"></script>
    <script src="{% static 'main/js/bootstrap-datetimepicker.ru.js' %}"></script>
    <script src="{% static 'main/js/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'main/js/bootstrap.bundle.min.js' %}"></script>






    {% block title %}
    {% endblock title %}
</head>
<body>
  <div class="container">
      <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
          <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
          <span class="fs-4">HRIS</span>
        </a>
        <ul class="nav nav-pills">
            {% if user.is_authenticated %}
            <li class="nav-item"><a href="{% url 'staff' %}" class="nav-link">Сотрудники</a></li>
             <li class="nav-item"><a href="{% url 'orders' %}" class="nav-link">Добавить сотрудника</a></li>
                <li class="nav-item"><a href="{% url 'request:record' %}" class="nav-link">Выдать ЗП</a></li>
            {% else %}
            {% endif %}

            {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link">{{ user }}</a> </li>
            <a class="nav-link active" href="{% url 'exit' %}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Выйти</a>

            <form id="logout-form" action="{% url 'exit' %}" method="post" style="display: none;">
                {% csrf_token %}
            </form>
            {% else %}
            <li class="nav-item"><a href="{% url 'user' %}" class="nav-link">Войти</a> </li>
            <li class="nav-item"><a href="{% url 'reg' %}" class="nav-link active">Регистрация</a> </li>
            {% endif %}
          </ul>
        </header>
      </div>
      {% if messages %}
        {% for mess in messages %}
          <div class="alert-success">
            {{ mess }}
          </div>
        {% endfor %}
      {% endif %}
      {% block body %} {% endblock body %}
      <div class="footer">
        <footer>© 2024 «HRIS». Все права защищены.
            <address>00000@gmail.com</address>
        </footer>
    </div>
</body>
</html>